version: '3.8'
services:
  app:
    container_name: jru-final-app
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      service-db:
        condition: service_healthy
    networks:
      - postgres

  service-db:
    container_name: postgres-container
    image: postgres:latest
    environment:
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
      POSTGRES_DB: jira
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
#      - ./infrastructure/db/dump.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d jira -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5


  pgadmin:
    container_name: pgadmin4-container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - service-db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres


volumes:
  db-data:
  pgadmin-data:


networks:
  postgres: